name: Main GitHub Page
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/main-gh-page.yml'
jobs:
  deploy:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - run: npm run deploy