name: Main GitHub Page
on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/main-pull-request-gh-page.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install packages
        run: npm install
      - name: Run predeploy script
        run: npm run predeploy