name: Main GitHub Page
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/main-gh-page.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - working-directory: frontend
        run: npm run deploy