name: Main GitHub Page
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/main-gh-page.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run deploy